// Code generated by ent, DO NOT EDIT.

package predicate

import (
	"entgo.io/ent/dialect/sql"
)

// LoginLog is the predicate function for loginlog builders.
type LoginLog func(*sql.Selector)

// User is the predicate function for user builders.
type User func(*sql.Selector)

// UserData is the predicate function for userdata builders.
type UserData func(*sql.Selector)
