// Code generated by ent, DO NOT EDIT.

package migrate

import (
	"entgo.io/ent/dialect/sql/schema"
	"entgo.io/ent/schema/field"
)

var (
	// LoginLogsColumns holds the columns for the "login_logs" table.
	LoginLogsColumns = []*schema.Column{
		{Name: "id", Type: field.TypeInt, Increment: true},
		{Name: "ip_addr", Type: field.TypeString},
		{Name: "login_time", Type: field.TypeTime},
		{Name: "user_login_logs", Type: field.TypeInt, Nullable: true},
	}
	// LoginLogsTable holds the schema information for the "login_logs" table.
	LoginLogsTable = &schema.Table{
		Name:       "login_logs",
		Columns:    LoginLogsColumns,
		PrimaryKey: []*schema.Column{LoginLogsColumns[0]},
		ForeignKeys: []*schema.ForeignKey{
			{
				Symbol:     "login_logs_users_login_logs",
				Columns:    []*schema.Column{LoginLogsColumns[3]},
				RefColumns: []*schema.Column{UsersColumns[0]},
				OnDelete:   schema.SetNull,
			},
		},
	}
	// UsersColumns holds the columns for the "users" table.
	UsersColumns = []*schema.Column{
		{Name: "id", Type: field.TypeInt, Increment: true},
		{Name: "email", Type: field.TypeString, Unique: true},
		{Name: "phone", Type: field.TypeString, Unique: true},
		{Name: "password", Type: field.TypeString},
		{Name: "reg_time", Type: field.TypeTime},
	}
	// UsersTable holds the schema information for the "users" table.
	UsersTable = &schema.Table{
		Name:       "users",
		Columns:    UsersColumns,
		PrimaryKey: []*schema.Column{UsersColumns[0]},
	}
	// UserDataColumns holds the columns for the "user_data" table.
	UserDataColumns = []*schema.Column{
		{Name: "id", Type: field.TypeInt, Increment: true},
		{Name: "nickname", Type: field.TypeString, Unique: true},
		{Name: "avatar_url", Type: field.TypeString, Default: ""},
		{Name: "birthday", Type: field.TypeTime},
		{Name: "sex", Type: field.TypeEnum, Enums: []string{"UnKnowSex", "Male", "Female"}, Default: "UnKnowSex"},
		{Name: "level_exp", Type: field.TypeInt, Default: 0},
		{Name: "user_user_data", Type: field.TypeInt, Unique: true},
	}
	// UserDataTable holds the schema information for the "user_data" table.
	UserDataTable = &schema.Table{
		Name:       "user_data",
		Columns:    UserDataColumns,
		PrimaryKey: []*schema.Column{UserDataColumns[0]},
		ForeignKeys: []*schema.ForeignKey{
			{
				Symbol:     "user_data_users_user_data",
				Columns:    []*schema.Column{UserDataColumns[6]},
				RefColumns: []*schema.Column{UsersColumns[0]},
				OnDelete:   schema.NoAction,
			},
		},
	}
	// Tables holds all the tables in the schema.
	Tables = []*schema.Table{
		LoginLogsTable,
		UsersTable,
		UserDataTable,
	}
)

func init() {
	LoginLogsTable.ForeignKeys[0].RefTable = UsersTable
	UserDataTable.ForeignKeys[0].RefTable = UsersTable
}
