// Code generated by ent, DO NOT EDIT.

package model

import (
	"context"
	"fmt"
	"math"

	"entgo.io/ent/dialect/sql"
	"entgo.io/ent/dialect/sql/sqlgraph"
	"entgo.io/ent/schema/field"
	"github.com/grin-ch/grin-auth/pkg/model/loginlog"
	"github.com/grin-ch/grin-auth/pkg/model/predicate"
	"github.com/grin-ch/grin-auth/pkg/model/user"
)

// LoginLogQuery is the builder for querying LoginLog entities.
type LoginLogQuery struct {
	config
	ctx        *QueryContext
	order      []OrderFunc
	inters     []Interceptor
	predicates []predicate.LoginLog
	withUser   *UserQuery
	withFKs    bool
	// intermediate query (i.e. traversal path).
	sql  *sql.Selector
	path func(context.Context) (*sql.Selector, error)
}

// Where adds a new predicate for the LoginLogQuery builder.
func (llq *LoginLogQuery) Where(ps ...predicate.LoginLog) *LoginLogQuery {
	llq.predicates = append(llq.predicates, ps...)
	return llq
}

// Limit the number of records to be returned by this query.
func (llq *LoginLogQuery) Limit(limit int) *LoginLogQuery {
	llq.ctx.Limit = &limit
	return llq
}

// Offset to start from.
func (llq *LoginLogQuery) Offset(offset int) *LoginLogQuery {
	llq.ctx.Offset = &offset
	return llq
}

// Unique configures the query builder to filter duplicate records on query.
// By default, unique is set to true, and can be disabled using this method.
func (llq *LoginLogQuery) Unique(unique bool) *LoginLogQuery {
	llq.ctx.Unique = &unique
	return llq
}

// Order specifies how the records should be ordered.
func (llq *LoginLogQuery) Order(o ...OrderFunc) *LoginLogQuery {
	llq.order = append(llq.order, o...)
	return llq
}

// QueryUser chains the current query on the "user" edge.
func (llq *LoginLogQuery) QueryUser() *UserQuery {
	query := (&UserClient{config: llq.config}).Query()
	query.path = func(ctx context.Context) (fromU *sql.Selector, err error) {
		if err := llq.prepareQuery(ctx); err != nil {
			return nil, err
		}
		selector := llq.sqlQuery(ctx)
		if err := selector.Err(); err != nil {
			return nil, err
		}
		step := sqlgraph.NewStep(
			sqlgraph.From(loginlog.Table, loginlog.FieldID, selector),
			sqlgraph.To(user.Table, user.FieldID),
			sqlgraph.Edge(sqlgraph.M2O, true, loginlog.UserTable, loginlog.UserColumn),
		)
		fromU = sqlgraph.SetNeighbors(llq.driver.Dialect(), step)
		return fromU, nil
	}
	return query
}

// First returns the first LoginLog entity from the query.
// Returns a *NotFoundError when no LoginLog was found.
func (llq *LoginLogQuery) First(ctx context.Context) (*LoginLog, error) {
	nodes, err := llq.Limit(1).All(setContextOp(ctx, llq.ctx, "First"))
	if err != nil {
		return nil, err
	}
	if len(nodes) == 0 {
		return nil, &NotFoundError{loginlog.Label}
	}
	return nodes[0], nil
}

// FirstX is like First, but panics if an error occurs.
func (llq *LoginLogQuery) FirstX(ctx context.Context) *LoginLog {
	node, err := llq.First(ctx)
	if err != nil && !IsNotFound(err) {
		panic(err)
	}
	return node
}

// FirstID returns the first LoginLog ID from the query.
// Returns a *NotFoundError when no LoginLog ID was found.
func (llq *LoginLogQuery) FirstID(ctx context.Context) (id int, err error) {
	var ids []int
	if ids, err = llq.Limit(1).IDs(setContextOp(ctx, llq.ctx, "FirstID")); err != nil {
		return
	}
	if len(ids) == 0 {
		err = &NotFoundError{loginlog.Label}
		return
	}
	return ids[0], nil
}

// FirstIDX is like FirstID, but panics if an error occurs.
func (llq *LoginLogQuery) FirstIDX(ctx context.Context) int {
	id, err := llq.FirstID(ctx)
	if err != nil && !IsNotFound(err) {
		panic(err)
	}
	return id
}

// Only returns a single LoginLog entity found by the query, ensuring it only returns one.
// Returns a *NotSingularError when more than one LoginLog entity is found.
// Returns a *NotFoundError when no LoginLog entities are found.
func (llq *LoginLogQuery) Only(ctx context.Context) (*LoginLog, error) {
	nodes, err := llq.Limit(2).All(setContextOp(ctx, llq.ctx, "Only"))
	if err != nil {
		return nil, err
	}
	switch len(nodes) {
	case 1:
		return nodes[0], nil
	case 0:
		return nil, &NotFoundError{loginlog.Label}
	default:
		return nil, &NotSingularError{loginlog.Label}
	}
}

// OnlyX is like Only, but panics if an error occurs.
func (llq *LoginLogQuery) OnlyX(ctx context.Context) *LoginLog {
	node, err := llq.Only(ctx)
	if err != nil {
		panic(err)
	}
	return node
}

// OnlyID is like Only, but returns the only LoginLog ID in the query.
// Returns a *NotSingularError when more than one LoginLog ID is found.
// Returns a *NotFoundError when no entities are found.
func (llq *LoginLogQuery) OnlyID(ctx context.Context) (id int, err error) {
	var ids []int
	if ids, err = llq.Limit(2).IDs(setContextOp(ctx, llq.ctx, "OnlyID")); err != nil {
		return
	}
	switch len(ids) {
	case 1:
		id = ids[0]
	case 0:
		err = &NotFoundError{loginlog.Label}
	default:
		err = &NotSingularError{loginlog.Label}
	}
	return
}

// OnlyIDX is like OnlyID, but panics if an error occurs.
func (llq *LoginLogQuery) OnlyIDX(ctx context.Context) int {
	id, err := llq.OnlyID(ctx)
	if err != nil {
		panic(err)
	}
	return id
}

// All executes the query and returns a list of LoginLogs.
func (llq *LoginLogQuery) All(ctx context.Context) ([]*LoginLog, error) {
	ctx = setContextOp(ctx, llq.ctx, "All")
	if err := llq.prepareQuery(ctx); err != nil {
		return nil, err
	}
	qr := querierAll[[]*LoginLog, *LoginLogQuery]()
	return withInterceptors[[]*LoginLog](ctx, llq, qr, llq.inters)
}

// AllX is like All, but panics if an error occurs.
func (llq *LoginLogQuery) AllX(ctx context.Context) []*LoginLog {
	nodes, err := llq.All(ctx)
	if err != nil {
		panic(err)
	}
	return nodes
}

// IDs executes the query and returns a list of LoginLog IDs.
func (llq *LoginLogQuery) IDs(ctx context.Context) ([]int, error) {
	var ids []int
	ctx = setContextOp(ctx, llq.ctx, "IDs")
	if err := llq.Select(loginlog.FieldID).Scan(ctx, &ids); err != nil {
		return nil, err
	}
	return ids, nil
}

// IDsX is like IDs, but panics if an error occurs.
func (llq *LoginLogQuery) IDsX(ctx context.Context) []int {
	ids, err := llq.IDs(ctx)
	if err != nil {
		panic(err)
	}
	return ids
}

// Count returns the count of the given query.
func (llq *LoginLogQuery) Count(ctx context.Context) (int, error) {
	ctx = setContextOp(ctx, llq.ctx, "Count")
	if err := llq.prepareQuery(ctx); err != nil {
		return 0, err
	}
	return withInterceptors[int](ctx, llq, querierCount[*LoginLogQuery](), llq.inters)
}

// CountX is like Count, but panics if an error occurs.
func (llq *LoginLogQuery) CountX(ctx context.Context) int {
	count, err := llq.Count(ctx)
	if err != nil {
		panic(err)
	}
	return count
}

// Exist returns true if the query has elements in the graph.
func (llq *LoginLogQuery) Exist(ctx context.Context) (bool, error) {
	ctx = setContextOp(ctx, llq.ctx, "Exist")
	switch _, err := llq.FirstID(ctx); {
	case IsNotFound(err):
		return false, nil
	case err != nil:
		return false, fmt.Errorf("model: check existence: %w", err)
	default:
		return true, nil
	}
}

// ExistX is like Exist, but panics if an error occurs.
func (llq *LoginLogQuery) ExistX(ctx context.Context) bool {
	exist, err := llq.Exist(ctx)
	if err != nil {
		panic(err)
	}
	return exist
}

// Clone returns a duplicate of the LoginLogQuery builder, including all associated steps. It can be
// used to prepare common query builders and use them differently after the clone is made.
func (llq *LoginLogQuery) Clone() *LoginLogQuery {
	if llq == nil {
		return nil
	}
	return &LoginLogQuery{
		config:     llq.config,
		ctx:        llq.ctx.Clone(),
		order:      append([]OrderFunc{}, llq.order...),
		inters:     append([]Interceptor{}, llq.inters...),
		predicates: append([]predicate.LoginLog{}, llq.predicates...),
		withUser:   llq.withUser.Clone(),
		// clone intermediate query.
		sql:  llq.sql.Clone(),
		path: llq.path,
	}
}

// WithUser tells the query-builder to eager-load the nodes that are connected to
// the "user" edge. The optional arguments are used to configure the query builder of the edge.
func (llq *LoginLogQuery) WithUser(opts ...func(*UserQuery)) *LoginLogQuery {
	query := (&UserClient{config: llq.config}).Query()
	for _, opt := range opts {
		opt(query)
	}
	llq.withUser = query
	return llq
}

// GroupBy is used to group vertices by one or more fields/columns.
// It is often used with aggregate functions, like: count, max, mean, min, sum.
//
// Example:
//
//	var v []struct {
//		IPAddr string `json:"ip_addr,omitempty"`
//		Count int `json:"count,omitempty"`
//	}
//
//	client.LoginLog.Query().
//		GroupBy(loginlog.FieldIPAddr).
//		Aggregate(model.Count()).
//		Scan(ctx, &v)
//
func (llq *LoginLogQuery) GroupBy(field string, fields ...string) *LoginLogGroupBy {
	llq.ctx.Fields = append([]string{field}, fields...)
	grbuild := &LoginLogGroupBy{build: llq}
	grbuild.flds = &llq.ctx.Fields
	grbuild.label = loginlog.Label
	grbuild.scan = grbuild.Scan
	return grbuild
}

// Select allows the selection one or more fields/columns for the given query,
// instead of selecting all fields in the entity.
//
// Example:
//
//	var v []struct {
//		IPAddr string `json:"ip_addr,omitempty"`
//	}
//
//	client.LoginLog.Query().
//		Select(loginlog.FieldIPAddr).
//		Scan(ctx, &v)
//
func (llq *LoginLogQuery) Select(fields ...string) *LoginLogSelect {
	llq.ctx.Fields = append(llq.ctx.Fields, fields...)
	sbuild := &LoginLogSelect{LoginLogQuery: llq}
	sbuild.label = loginlog.Label
	sbuild.flds, sbuild.scan = &llq.ctx.Fields, sbuild.Scan
	return sbuild
}

// Aggregate returns a LoginLogSelect configured with the given aggregations.
func (llq *LoginLogQuery) Aggregate(fns ...AggregateFunc) *LoginLogSelect {
	return llq.Select().Aggregate(fns...)
}

func (llq *LoginLogQuery) prepareQuery(ctx context.Context) error {
	for _, inter := range llq.inters {
		if inter == nil {
			return fmt.Errorf("model: uninitialized interceptor (forgotten import model/runtime?)")
		}
		if trv, ok := inter.(Traverser); ok {
			if err := trv.Traverse(ctx, llq); err != nil {
				return err
			}
		}
	}
	for _, f := range llq.ctx.Fields {
		if !loginlog.ValidColumn(f) {
			return &ValidationError{Name: f, err: fmt.Errorf("model: invalid field %q for query", f)}
		}
	}
	if llq.path != nil {
		prev, err := llq.path(ctx)
		if err != nil {
			return err
		}
		llq.sql = prev
	}
	return nil
}

func (llq *LoginLogQuery) sqlAll(ctx context.Context, hooks ...queryHook) ([]*LoginLog, error) {
	var (
		nodes       = []*LoginLog{}
		withFKs     = llq.withFKs
		_spec       = llq.querySpec()
		loadedTypes = [1]bool{
			llq.withUser != nil,
		}
	)
	if llq.withUser != nil {
		withFKs = true
	}
	if withFKs {
		_spec.Node.Columns = append(_spec.Node.Columns, loginlog.ForeignKeys...)
	}
	_spec.ScanValues = func(columns []string) ([]any, error) {
		return (*LoginLog).scanValues(nil, columns)
	}
	_spec.Assign = func(columns []string, values []any) error {
		node := &LoginLog{config: llq.config}
		nodes = append(nodes, node)
		node.Edges.loadedTypes = loadedTypes
		return node.assignValues(columns, values)
	}
	for i := range hooks {
		hooks[i](ctx, _spec)
	}
	if err := sqlgraph.QueryNodes(ctx, llq.driver, _spec); err != nil {
		return nil, err
	}
	if len(nodes) == 0 {
		return nodes, nil
	}
	if query := llq.withUser; query != nil {
		if err := llq.loadUser(ctx, query, nodes, nil,
			func(n *LoginLog, e *User) { n.Edges.User = e }); err != nil {
			return nil, err
		}
	}
	return nodes, nil
}

func (llq *LoginLogQuery) loadUser(ctx context.Context, query *UserQuery, nodes []*LoginLog, init func(*LoginLog), assign func(*LoginLog, *User)) error {
	ids := make([]int, 0, len(nodes))
	nodeids := make(map[int][]*LoginLog)
	for i := range nodes {
		if nodes[i].user_login_logs == nil {
			continue
		}
		fk := *nodes[i].user_login_logs
		if _, ok := nodeids[fk]; !ok {
			ids = append(ids, fk)
		}
		nodeids[fk] = append(nodeids[fk], nodes[i])
	}
	if len(ids) == 0 {
		return nil
	}
	query.Where(user.IDIn(ids...))
	neighbors, err := query.All(ctx)
	if err != nil {
		return err
	}
	for _, n := range neighbors {
		nodes, ok := nodeids[n.ID]
		if !ok {
			return fmt.Errorf(`unexpected foreign-key "user_login_logs" returned %v`, n.ID)
		}
		for i := range nodes {
			assign(nodes[i], n)
		}
	}
	return nil
}

func (llq *LoginLogQuery) sqlCount(ctx context.Context) (int, error) {
	_spec := llq.querySpec()
	_spec.Node.Columns = llq.ctx.Fields
	if len(llq.ctx.Fields) > 0 {
		_spec.Unique = llq.ctx.Unique != nil && *llq.ctx.Unique
	}
	return sqlgraph.CountNodes(ctx, llq.driver, _spec)
}

func (llq *LoginLogQuery) querySpec() *sqlgraph.QuerySpec {
	_spec := &sqlgraph.QuerySpec{
		Node: &sqlgraph.NodeSpec{
			Table:   loginlog.Table,
			Columns: loginlog.Columns,
			ID: &sqlgraph.FieldSpec{
				Type:   field.TypeInt,
				Column: loginlog.FieldID,
			},
		},
		From:   llq.sql,
		Unique: true,
	}
	if unique := llq.ctx.Unique; unique != nil {
		_spec.Unique = *unique
	}
	if fields := llq.ctx.Fields; len(fields) > 0 {
		_spec.Node.Columns = make([]string, 0, len(fields))
		_spec.Node.Columns = append(_spec.Node.Columns, loginlog.FieldID)
		for i := range fields {
			if fields[i] != loginlog.FieldID {
				_spec.Node.Columns = append(_spec.Node.Columns, fields[i])
			}
		}
	}
	if ps := llq.predicates; len(ps) > 0 {
		_spec.Predicate = func(selector *sql.Selector) {
			for i := range ps {
				ps[i](selector)
			}
		}
	}
	if limit := llq.ctx.Limit; limit != nil {
		_spec.Limit = *limit
	}
	if offset := llq.ctx.Offset; offset != nil {
		_spec.Offset = *offset
	}
	if ps := llq.order; len(ps) > 0 {
		_spec.Order = func(selector *sql.Selector) {
			for i := range ps {
				ps[i](selector)
			}
		}
	}
	return _spec
}

func (llq *LoginLogQuery) sqlQuery(ctx context.Context) *sql.Selector {
	builder := sql.Dialect(llq.driver.Dialect())
	t1 := builder.Table(loginlog.Table)
	columns := llq.ctx.Fields
	if len(columns) == 0 {
		columns = loginlog.Columns
	}
	selector := builder.Select(t1.Columns(columns...)...).From(t1)
	if llq.sql != nil {
		selector = llq.sql
		selector.Select(selector.Columns(columns...)...)
	}
	if llq.ctx.Unique != nil && *llq.ctx.Unique {
		selector.Distinct()
	}
	for _, p := range llq.predicates {
		p(selector)
	}
	for _, p := range llq.order {
		p(selector)
	}
	if offset := llq.ctx.Offset; offset != nil {
		// limit is mandatory for offset clause. We start
		// with default value, and override it below if needed.
		selector.Offset(*offset).Limit(math.MaxInt32)
	}
	if limit := llq.ctx.Limit; limit != nil {
		selector.Limit(*limit)
	}
	return selector
}

// LoginLogGroupBy is the group-by builder for LoginLog entities.
type LoginLogGroupBy struct {
	selector
	build *LoginLogQuery
}

// Aggregate adds the given aggregation functions to the group-by query.
func (llgb *LoginLogGroupBy) Aggregate(fns ...AggregateFunc) *LoginLogGroupBy {
	llgb.fns = append(llgb.fns, fns...)
	return llgb
}

// Scan applies the selector query and scans the result into the given value.
func (llgb *LoginLogGroupBy) Scan(ctx context.Context, v any) error {
	ctx = setContextOp(ctx, llgb.build.ctx, "GroupBy")
	if err := llgb.build.prepareQuery(ctx); err != nil {
		return err
	}
	return scanWithInterceptors[*LoginLogQuery, *LoginLogGroupBy](ctx, llgb.build, llgb, llgb.build.inters, v)
}

func (llgb *LoginLogGroupBy) sqlScan(ctx context.Context, root *LoginLogQuery, v any) error {
	selector := root.sqlQuery(ctx).Select()
	aggregation := make([]string, 0, len(llgb.fns))
	for _, fn := range llgb.fns {
		aggregation = append(aggregation, fn(selector))
	}
	if len(selector.SelectedColumns()) == 0 {
		columns := make([]string, 0, len(*llgb.flds)+len(llgb.fns))
		for _, f := range *llgb.flds {
			columns = append(columns, selector.C(f))
		}
		columns = append(columns, aggregation...)
		selector.Select(columns...)
	}
	selector.GroupBy(selector.Columns(*llgb.flds...)...)
	if err := selector.Err(); err != nil {
		return err
	}
	rows := &sql.Rows{}
	query, args := selector.Query()
	if err := llgb.build.driver.Query(ctx, query, args, rows); err != nil {
		return err
	}
	defer rows.Close()
	return sql.ScanSlice(rows, v)
}

// LoginLogSelect is the builder for selecting fields of LoginLog entities.
type LoginLogSelect struct {
	*LoginLogQuery
	selector
}

// Aggregate adds the given aggregation functions to the selector query.
func (lls *LoginLogSelect) Aggregate(fns ...AggregateFunc) *LoginLogSelect {
	lls.fns = append(lls.fns, fns...)
	return lls
}

// Scan applies the selector query and scans the result into the given value.
func (lls *LoginLogSelect) Scan(ctx context.Context, v any) error {
	ctx = setContextOp(ctx, lls.ctx, "Select")
	if err := lls.prepareQuery(ctx); err != nil {
		return err
	}
	return scanWithInterceptors[*LoginLogQuery, *LoginLogSelect](ctx, lls.LoginLogQuery, lls, lls.inters, v)
}

func (lls *LoginLogSelect) sqlScan(ctx context.Context, root *LoginLogQuery, v any) error {
	selector := root.sqlQuery(ctx)
	aggregation := make([]string, 0, len(lls.fns))
	for _, fn := range lls.fns {
		aggregation = append(aggregation, fn(selector))
	}
	switch n := len(*lls.selector.flds); {
	case n == 0 && len(aggregation) > 0:
		selector.Select(aggregation...)
	case n != 0 && len(aggregation) > 0:
		selector.AppendSelect(aggregation...)
	}
	rows := &sql.Rows{}
	query, args := selector.Query()
	if err := lls.driver.Query(ctx, query, args, rows); err != nil {
		return err
	}
	defer rows.Close()
	return sql.ScanSlice(rows, v)
}
